### ISSUE TITLE
Uncompilable!

### ISSUE THREAD

**Issue by Kakadu** [ocsigen/eliom-widgets#2]
Have I forgot some dependencies?

```
$ make
mkdir -p _deps
mkdir -p _deps/src/ _deps/src/button/
mkdir -p _deps/src/ _deps/src/button/
eliomdep -server -package text -I src/ -I src/button/ src/ew_accents.eliom > _deps/src/ew_accents.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/ew_button.eliom > _deps/src/ew_button.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/ew_dyn_upload.eliom > _deps/src/ew_dyn_upload.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/ew_dyn_upload.eliomi > _deps/src/ew_dyn_upload.eliomi.server
eliomdep -server -package text -I src/ -I src/button/ src/ew_editable.eliom > _deps/src/ew_editable.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/ew_editable.eliomi > _deps/src/ew_editable.eliomi.server
eliomdep -server -package text -I src/ -I src/button/ src/button/button_alert_.eliom > _deps/src/button/button_alert_.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/button/button_.eliom > _deps/src/button/button_.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/button/button_show_hide_.eliom > _deps/src/button/button_show_hide_.eliom.server
eliomdep -server -package text -I src/ -I src/button/ src/button/button_show_hide_focus_.eliom > _deps/src/button/button_show_hide_focus_.eliom.server
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/ew_accents.eliom > _deps/src/ew_accents.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/ew_button.eliom > _deps/src/ew_button.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/ew_dyn_upload.eliom > _deps/src/ew_dyn_upload.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/ew_dyn_upload.eliomi > _deps/src/ew_dyn_upload.eliomi.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/ew_editable.eliom > _deps/src/ew_editable.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/ew_editable.eliomi > _deps/src/ew_editable.eliomi.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/button/button_alert_.eliom > _deps/src/button/button_alert_.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/button/button_.eliom > _deps/src/button/button_.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/button/button_show_hide_.eliom > _deps/src/button/button_show_hide_.eliom.client
eliomdep -client -package ojwidgets -I src/ -I src/button/ src/button/button_show_hide_focus_.eliom > _deps/src/button/button_show_hide_focus_.eliom.client
cat _deps/src/ew_accents.eliom.server _deps/src/ew_button.eliom.server _deps/src/ew_dyn_upload.eliom.server _deps/src/ew_dyn_upload.eliomi.server _deps/src/ew_editable.eliom.server _deps/src/ew_editable.eliomi.server _deps/src/button/button_alert_.eliom.server _deps/src/button/button_.eliom.server _deps/src/button/button_show_hide_.eliom.server _deps/src/button/button_show_hide_focus_.eliom.server _deps/src/ew_accents.eliom.client _deps/src/ew_button.eliom.client _deps/src/ew_dyn_upload.eliom.client _deps/src/ew_dyn_upload.eliomi.client _deps/src/ew_editable.eliom.client _deps/src/ew_editable.eliomi.client _deps/src/button/button_alert_.eliom.client _deps/src/button/button_.eliom.client _deps/src/button/button_show_hide_.eliom.client _deps/src/button/button_show_hide_focus_.eliom.client > .depend
eliomc -c -package text -I _server/src/ -I _server/src/button/  src/ew_accents.eliom
eliomc -c -package text -I _server/src/ -I _server/src/button/  src/ew_button.eliom
File "src/ew_button.eliom", line 2, characters 10-17:
Error: Unbound module Button_
make: *** [_server/src/ew_button.cmo] Error 2
```

**Comment by ccharly** [comment]
If you're using the latest version of eliom, this commit has broken the compilation of eliom-widgets: https://github.com/ocsigen/eliom/commit/7be0916df98f68aaad7993f8c40a3c7150b26567

Because of the '/' into the include directory, eliom thinks that not on the current directory and it do not prepend _server or _client to it.

We have already find another solution to this commit for files which are not eliom files. I'm going to submit a pull-request soon to fix that on eliom.

If you want to use eliom-widgets without downgrading your eliom's version, here my [.depend](http://pastebin.com/PxuVi8vB).

(I will close this issue when eliom will have fix this include issue ! :))

**Comment by Kakadu** [comment]
It seems `eliom-base-app` have the  compilation issue too. Is it's problem the same? If yes, can you provide '.depend', please?

**Comment by ccharly** [comment]
Yes it's the same issue.

Here the [.depend](http://pastebin.com/ynd0QS3e).
I just want to tell you that eliom-base-app will change in few days, i'm working on a version much more customisable, and the current version version wont be compatible with the new one.

**Comment by ccharly** [comment]
miss click, sorry ;)

**Comment by Kakadu** [comment]
> ....  eliom-base-app will change in few days

I can't wait to see it

**Comment by Kakadu** [comment]
And, please, don't forget to add to README instructions how to run server with eliom_base_app locally.

**Comment by ccharly** [comment]
yep I'm working on the new version, so I will obviously add a README to show how to setup the library, don't worry about that ;).

**Comment by Kakadu** [comment]
> I just want to tell you that eliom-base-app will change in few days

Any news?

**Comment by ccharly** [comment]
Hi, you can see the changes [here](https://github.com/ocsigen/eliom-base-app/tree/experiments). It's currently in work in progress, but I think that at the end of the week, the release version will be "mainly" finished. (if you want an exemple of how to set up EBA, take a look to the 'samples' directory).

Beware, this version could change in the week ;).

**Comment by Kakadu** [comment]
It seems that You've added `Eba_user` module and I needed to add few bytes to previous version of `.depend` to compile. But after doing this I have seen

```
js_of_eliom -c -package text,calendar,ojwidgets,eliom-widgets.client -I _client/./  eba_db.ml
File "eba_db.ml", line 129, characters 29-70:
While finding quotation "sequence" in a position of "expr":
  Available quotation expanders are:
    svglist (in a position of expr)
    svg (in a position of expr)
    html5list (in a position of expr)
    html5 (in a position of expr)
    xhtmllist (in a position of expr)
    xhtml (in a position of expr)

  Camlp4: Uncaught exception: Not_found

File "eba_db.ml", line 1:
Error: Preprocessor error
make: *** [_client/eba_db.cmo] Error 2
```

probably macaque syntax extension is not added or it was used in a wrong file (can we really compose eliom's syntax extension with Camlp4 ones?). Anyway it seems that it's better for me to wait for your "release".

Happy hacking

**Comment by ccharly** [comment]
hi, here the new [.depend](http://pastebin.com/peJ7G06W).

I don't have any errors with the current version of the repository. You've got this error because you are using `js_of_eliom` (client side) for `eba_db.ml` file which is only a server side file (see the [Makefile.options](https://github.com/ocsigen/eliom-base-app/blob/master/Makefile.options#L12) of eliom-base-app).

**Comment by Kakadu** [comment]
The compilation issue appeared because I was fixing '.depend' manually, now it is OK

Does `samples` directory needs specific `.depend` as before?

Also, in `sample/README.md` you are referring to OL package which is in `installation` directory which doesn't exist. What OL means is not described too. Probably `README` is outdated.

**Comment by ccharly** [comment]
yep indeed the `README.md` from `samples` directory is outdated.

For the `.depend` of `samples`, you do not need a specific one.

**Comment by ccharly** [comment]
I'm going to submit a pull-request to fix `eliomdep` binary today. I spoke with some other ocsigen developers and my patch seems to be good. I just need more test before submit it.

**Comment by Kakadu** [comment]
okay, it runs but.

1) I can't figure purpose of `set_admin.sh`. Anyway it should be executed with `bash` and not `sh` because syntax error.
2) I can see web-face but registration is broken (because I have no postfix installed). A have added manually my password to database than but I still can't login because it says `Wrong password`. It seems I have done something wrong.
3) During page rendering it gives error
GET http://localhost:8080/css/myproject.css 404 Not Found       1ms
because `symlink myproject.css -> myproject-theme3-v.css` is broken

**Comment by ccharly** [comment]
indeed, some parts of the projects are currently broken. I'm currently thinking about how to design `eliom-base-app` to make it really easy to use.

1) for `set_admin.sh` it was just a little script that I did a long time ago and I do not use it anymore (I'm going to use a `.ml` file instead of, using macaque)

2) for the password, indeed you can't set it directly by put it manually, because of the hash functions used by `eba`.

3) I didn't clean the repo ;) but normally, it's not really a problem.

Just to tell that `eba` has only a few styles for now, I think that I'm going to add more of them to make it more beautiful.

**Comment by Kakadu** [comment]
2) I have succeeded to add password to database and I can login and see button to upload avatar. By some reason I can't see anything else on the page. Probably, it's mentioned above CSS issue

P.S. How it is going? Will you finish next version until September?

**Comment by ccharly** [comment]
Hi, normally i will finish it in the next week :)

**Comment by Drup** [comment]
I think it's fixed for quite a long time so, closing it.

**Comment by Ke-Dou** [comment]
Hi, I also got an similar error:

```
File "testDB.ml", line 21, characters 14-81 (end at line 24, character 4):
While finding quotation "table" in a position of "expr":
Available quotation expanders are:
svglist (in a position of expr)
svg (in a position of expr)
html5list (in a position of expr)
html5 (in a position of expr)
xhtmllist (in a position of expr)
xhtml (in a position of expr)

Camlp4: Uncaught exception: Not_found
```

Do you guys know how to fix it?
I have added "SERVER_PACKAGE := macaque.syntax" in my "Makefile.option".
Thanks.

**Comment by ccharly** [comment]
Can you please pastebin the content of your file `testDB.ml` please ?

**Comment by Ke-Dou** [comment]
Hi,

I just fixed the problem by changing "SERVER_PACKAGE := macaque.syntax" to
"SERVER_PACKAGES := macaque.syntax".
There is a "S" missed in your tutorial, so the macaque syntax package is
not added successfully.
Please also update this to your tutorial, so other learners won't get the
same error.
Thank you very much!

The related files are attached just in case that you still need them.

--Ke
